# Knora 4.0 文档配置

site_name: Knora 4.0 平台操作说明
site_description: 北京悦点科技有限公司 Knora 平台 4.0 智能体生成平台操作说明
site_author: 北京悦点科技有限公司
site_url: https://az-product.pages.brightendata.cn/All-In-On-Analysis/Knora-4.0-docs
docs_dir: docs
copyright: Copyright&copy;2026 北京悦点科技有限公司 - 京ICP备2022030803号

# Configuration
theme:
  name: material
  language: zh
  custom_dir: overrides
  logo: 'icon/knora-logo.png'
  favicon: 'icon/favicon.ico'
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.top
    - header.autohide
    - content.tabs.link

  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - stylesheets/logo.css
  - stylesheets/note.css
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - admonition  # 提示块
  - footnotes  # 脚注
  - meta  # 定义元数据
  - pymdownx.caret  # 下划线上标
  - pymdownx.tilde  # 删除线下标
  - pymdownx.critic  # 增加删除修改高亮注释
  - pymdownx.details  # 提示块可折叠
  - pymdownx.inlinehilite  # 行内代码高亮
  - pymdownx.mark  # 文本高亮
  - pymdownx.smartsymbols  # 符号转换
  - pymdownx.superfences  # 代码嵌套在列表里
  - codehilite: # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc: # 锚点
      permalink: true
  - pymdownx.betterem: # 对加粗和斜体更好的检测
      smart_enable: all
  - pymdownx.tasklist: # 复选框checklist
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

# Plugins
plugins:
  - glightbox:
      zoomable: true
  - search:
      prebuild_index: true
  - macros:
      include_dir: docs/reuse/
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_datetime
      fallback_to_build_date: true
  - with-pdf:
      verbose: true
      copyright: Copyright@2026 北京悦点科技有限公司 Brightendata Inc.
      cover_subtitle: v4.0
      author: 北京悦点科技有限公司
      cover: true
      back_cover: true
      output_path: pdf/Knora 平台 4.0 操作说明.pdf

extra_javascript:
  - js/config.js
  - js/jquery.js
  - js/init.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  version:
    provider: xingjiawei
  aio:
    name: Knora 平台
    cn_name: 企业级 Ontology Based Agentic AI 平台
    release: 4.0
    tag: v4.0

nav:
  - 前言: index.md
  - 欢迎使用Knora 平台:
      - 平台介绍: 1.introduce/abstract.md
      - 主要功能: 1.introduce/function.md
      - 相关词说明: 1.introduce/index.md
  - 本体管理: 2.manual/ontology_management.md
      - 语义图谱: 2.manual/ontology_management/ontology.md
      - 业务对象管理: 2.manual/ontology_management/entity.md
      - 业务关联管理: 2.manual/ontology_management/relation.md
      - 事实明细管理: 2.manual/ontology_management/event.md
      - 业务操作与行为: 2.manual/ontology_management/action.md
      - 本体自动构建: 2.manual/ontology_management/auto_build.md
      - 流程活动: 2.manual/ontology_management/Logic.md
      - 自主推理: 2.manual/ontology_management/knora_claw.md
      - 工具: 2.manual/ontology_management/tools.md
  - 模型配置: 2.manual/models.md
  - 用户界面: 2.manual/app.md
  - 图析: 2.manual/graph_analysis.md
  - 知识库: 2.manual/knowledge_base.md
  - 数据资产: 2.manual/data_asset.md
  - 经纶: 2.manual/pipeline.md
  - 密钥管理: 2.manual/key_management.md
